name: Code Coverage

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clean build directory
        run: rm -rf build/

      - name: Set up CMake
        run: cmake -DCMAKE_BUILD_TYPE=Coverage -S . -B build

      - name: Build
        run: cmake --build build

      - name: Run tests
        run: ./build/hello_test

      - name: Run main
        run: ./build/main

      - name: Install lcov
        run: sudo apt-get install -y lcov

      - name: Generate coverage report
        run: |
          lcov --capture --directory . --output-file coverage.info
          lcov --remove coverage.info '/usr/*' --output-file coverage.info
          lcov --remove coverage.info 'tests/*' --output-file coverage.info
          lcov --remove coverage.info 'build/*' --output-file coverage.info
          lcov --remove coverage.info '*/gtest/*' --output-file coverage.info
          lcov --remove coverage.info '*_test.cpp' --output-file coverage.info
          lcov --remove coverage.info '**/src/*' --output-file coverage.info
          genhtml coverage.info --output-directory coverage_report

      - name: Upload coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage_report
